name: Guardian Tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install dependencies
        run: yarn
      - name: Install playwright browsers
        run: yarn playwright install --with-deps
      - name: Run Guardian tests
        run: |
          yarn tsx tests/getRTokens.ts > tests/RTokens.json
          yarn test:e2e
        env:
          GUARDIAN_UI_ALCHEMY_API_KEY: ${{ secrets.GUARDIAN_UI_ALCHEMY_API_KEY }}
          CI: true
          REACT_APP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/lcamargof/reserve
          REACT_APP_CHAIN_ID: 1
          REACT_APP_RPAY_FEED: feed.rpay.app
          REACT_APP_ONE_INCH_URLS: |
            https://cold-mouse-7d43.mig2151.workers.dev,\
            https://blue-cake-3548.mig2151.workers.dev,\
            https://bitter-tree-ed5a.mig2151.workers.dev,\
            https://square-morning-0921.mig2151.workers.dev/
          GUARDIAN_UI_ANVIL_FLAGS: '--compute-units-per-second 100 --fork-retry-backoff 5000'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
